### ISSUE TITLE
В релиз залита дебаг сборка, у меня она не устанавливается🥲🥲🥲 Пришлось самому собирать

### ISSUE THREAD

**Issue by azpantic** [PhilipPeric/new_todo_app#1]

**Comment by PhilipPeric** [comment]
Сорри впервые билдил, собралось? не подскажешь, это надо какой-то флаг передать для недебаг сборки?

**Comment by PhilipPeric** [comment]
Залил релизную сборку

**Comment by rn7cvj** [comment]
Собирай этой командой
`flutter build apk --split-per-abi`
так будет сборка раздельная и apk будет весить меньше (там собираются разные apk под разные битности системы) но чаще всего v8 будет ставиться везде
